version: 2.1

orbs:
  node: circleci/node@1.1.6
  aws_s3: circleci/aws-s3@1.0.15

jobs:
  build:
    working_directory: ~/snowflake-inspector/snowflake-inspector
    executor:
      name: node/default
    steps:
      - checkout:
          path: ~/snowflake-inspector
      - node/with-cache:
          steps:
            - run: npm install
      - run: npx webpack --mode=production
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: ~/snowflake-inspector/snowflake-inspector
          # Must be relative path from root
          paths:
            - dist
  deploy:
    context: snowflakeinspector.com # this context stores all envs for this job
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: ls /tmp/workspace/dist
      - aws_s3/sync:
          from: /tmp/workspace/dist
          overwrite: true
          to: "s3://snowflakeinspector.com"

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
