version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd snowflake-inspector && npm install
      - run: cd snowflake-inspector && npx webpack --mode=production
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: snowflake-inspector
          # Must be relative path from root
          paths:
            - dist
workflows:
  build_and_deploy:
    jobs:
      - build